---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-java

inputs:
  - name: the-train

outputs:
  - name: build

run:
  path: the-train/ci/scripts/build.sh
